---
include:
  - project: development/gitlab-includes/services
    ref: 4.2.3
    file: trigger-composer-repository.yml
  - project: development/gitlab-includes/services
    ref: 1.3.0
    file: defaults.yml
  - project: development/gitlab-includes/services
    ref: 1.3.0
    file: php-lint.yml
  - project: development/gitlab-includes/services
    ref: 1.3.0
    file: php-unit.yml
  - project: development/gitlab-includes/services
    ref: 1.3.0
    file: trigger-general-docs.yml
