---
version: '3.7'

services:
  php-cli:
    image: eu.gcr.io/intermax-group-262516/tools/composer:latest
    shm_size: 1024m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes: [{type: bind, source: ./, target: /var/www/html}]
    stdin_open: true
    tty: true
    environment:
      PHP_OPEN_BASEDIR: "/var/www/html/:/dev/shm/:/composer/:/usr/local/bin/:/.dockerenv:/proc/cpuinfo:/opt/"
