---
version: '3.7'

services:
  php-cli:
    image: repo.harbor.intermax.nl/dockerhub-proxy/intermaxgroup/composer:latest
    shm_size: 1024m
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    volumes: [{type: bind, source: ./, target: /var/www/html}]
    stdin_open: true
    tty: true
